version: '2.4'

services:

  speedchecker:
    image: vuln-watch
    build: .
    tty: true
    container_name: vuln-watch
    # restart always = if unhealthy re-start the container
    restart: always
  
    volumes:
      - /dev/urandom:/dev/random
      - ./vuln-watch/:/opt/vuln-watch
      - ./s-nail.rc:/etc/s-nail.rc


    command: /opt/vuln-watch/run.sh

    # # check health here:   docker inspect --format='{{json .State.Health}}' rtl433_weewx | jq .
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "/usr/local/bin/healthcheck.sh",
    #     ]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   # delay long enough for weewx to gather an update and send to WU 
    #   start_period: 3m


